# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xoPCRXnTLySBUH7j-Mhmfv-tdkDcynUK
"""

import nltk
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

def analyze_sentiment(Sentence):
  analyzer = SentimentIntensityAnalyzer()
  return analyzer.polarity_scores(str(Sentence))

data = pd.read_csv('Sentiment_Stock_data.csv')

data['sentiment'] = data['Sentence'].apply(analyze_sentiment)

for i, row in data.iterrows():
  print(f"News: {row['Sentence']}")
  print(f"Sentiment: {row['sentiment']}")